FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:latest-run
ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
RUN apk update && apk add --no-cache avahi augeas

COPY entrypoint.sh /usr/src/

ENTRYPOINT ["/bin/sh", "/usr/src/entrypoint.sh"]
