version: "2"

volumes:
  spotifycache:
  mpd:
  mpd_fallback:
services:
  # Core services
  # -- Required for a fully featured installation of balenaSound
  # -- Mutiroom services can be removed if not using multiroom mode
  audio:
    build: ./core/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
  sound-supervisor:
    build:
      context: .
      dockerfile: ./core/sound-supervisor/Dockerfile.template
    network_mode: host
    labels:
      io.balena.features.balena-api: "1"
      io.balena.features.supervisor-api: 1

  multiroom-server:
    build: ./core/multiroom/server
    restart: on-failure
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780

  multiroom-client:
    build: ./core/multiroom/client
    restart: on-failure

  # Plugins
  # -- Additional plugins can be added. See https://balena-sound.pages.dev/plugins
  # -- Remove unwanted plugins as needed
  bluetooth:
    build: ./plugins/bluetooth
    restart: on-failure
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1

  airplay:
    build: ./plugins/airplay
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1

  dbus-session:
    build: ./plugins/dbus
    restart: on-failure
    network_mode: host
    privileged: true
    environment:
      - DBUS_CONFIG=session.conf
    labels:
      io.balena.features.dbus: 1
  mpd:
    build: ./plugins/mpd
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
     - mpd:/var/lib/mpd
     - mpd_fallback:/var/lib/fallback
  mpd-mpris:
    build: ./plugins/mpd-mpris
    restart: unless-stopped
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - 'container=docker'
      - 'DBUS_SESSION_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    depends_on:
      - mpd
      - dbus-session
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    security_opt:
      - 'apparmor:unconfined'
  mpc-control-with-ir:
    build: ./plugins/mpc-control-with-ir
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - 'container=docker'
      - 'DBUS_SESSION_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    restart: on-failure
    network_mode: host
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    security_opt:
      - 'apparmor:unconfined'
    labels:
      io.balena.features.dbus: 1
    depends_on:
      - mpd
      - dbus-session
  avahi:
    build: ./plugins/avahi
    network_mode: host
    restart: on-failure
  spotify:
    build: ./plugins/spotify
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - spotifycache:/var/cache/raspotify

  # https://github.com/balenablocks/hostname
  hostname:
    build: ./core/hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: balena
